"""add delete data cascade in device

Revision ID: 56f8531dc8ad
Revises: 4450d349ed54
Create Date: 2025-06-27 00:10:40.790234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f8531dc8ad'
down_revision: Union[str, Sequence[str], None] = '4450d349ed54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device_data', ['id'])
    op.drop_constraint(op.f('device_data_device_id_fkey'), 'device_data', type_='foreignkey')
    op.create_foreign_key(None, 'device_data', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'devices', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'device_data', type_='foreignkey')
    op.create_foreign_key(op.f('device_data_device_id_fkey'), 'device_data', 'devices', ['device_id'], ['id'])
    op.drop_constraint(None, 'device_data', type_='unique')
    # ### end Alembic commands ###
