name: Deploy to Server

on:
  workflow_run:
    workflows: ["Deploy to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy on server
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          # Создаём папку, если её нет
          mkdir -p ~/empolimer
          cd ~/empolimer

          # Загружаем переменные окружения на сервер
          echo "${{ secrets.ENV_VARS }}" > ~/empolimer/.env
          echo "Файл .env загружен на сервер"

          curl -o ~/empolimer/docker-compose.prod.yaml https://raw.githubusercontent.com/aleksioprime/sk-empolimer/main/docker-compose.prod.yaml

          # Если nginx.conf НЕ существует, скачиваем его
          if [ ! -f ~/empolimer/nginx/nginx.conf ]; then
            echo "Файл nginx.conf не найден. Скачиваем..."
            curl -v -o ~/empolimer/nginx/nginx.conf https://raw.githubusercontent.com/aleksioprime/sk-empolimer/main/web/front/nginx/nginx.conf
            ls -l ~/empolimer/nginx
          else
            echo "Файл nginx.conf уже существует. Не скачиваем."
          fi

          docker compose -f docker-compose.prod.yaml down
          docker compose -f docker-compose.prod.yaml pull
          docker compose -f docker-compose.prod.yaml up -d --remove-orphans
        EOF
