x-app: &app
  env_file:
    - ./.env
  restart: always
  platform: linux/amd64

services:
  postgres:
    image: postgres:14
    container_name: empolimer-postgres
    <<: *app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

  redis:
    image: redis:6
    container_name: empolimer-redis
    <<: *app
    volumes:
      - redis_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: aleksioprime/empolimer-back:latest
    container_name: empolimer-back
    <<: *app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  worker:
    image: aleksioprime/empolimer-worker:latest
    container_name: empolimer-worker
    <<: *app
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started

  frontend:
    image: aleksioprime/empolimer-front:latest
    <<: *app
    container_name: empolimer-front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /root/empolimer/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_started

  adminer:
    image: adminer
    container_name: empolimer-adminer
    <<: *app
    ports:
      - "81:8080"
    depends_on:
      postgres:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: empolimer-mqtt
    <<: *app
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  nodered:
    image: nodered/node-red
    container_name: empolimer-nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/settings.js:/data/settings.js
      - nodered_data:/data
    depends_on:
      mosquitto:
        condition: service_started

volumes:
  postgres_volume:
  redis_volume:
  mosquitto_data:
  mosquitto_log:
  nodered_data: