x-app: &app
  env_file:
    - ./.env
  restart: always
  platform: linux/amd64

services:
  postgres:
    image: postgres:14
    container_name: empolimer-postgres
    <<: *app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

  redis:
    image: redis:6
    container_name: empolimer-redis
    <<: *app
    volumes:
      - redis_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./back
    container_name: empolimer-backend
    <<: *app
    volumes:
      - ./back:/usr/src/app/
    ports:
      - "8201:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  worker:
    build:
      context: ./worker
    container_name: empolimer-worker
    <<: *app
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started

  frontend:
    build:
      context: ./front
      target: dev
      args:
        - VITE_LOGGING=${VITE_LOGGING}
        - VITE_SERVICE_URL=${VITE_SERVICE_URL}
    <<: *app
    container_name: empolimer-frontend
    volumes:
      - ./front/app/src:/usr/src/app/src
    ports:
      - "8202:5173"
    depends_on:
      backend:
        condition: service_started

  adminer:
    image: adminer
    container_name: empolimer-adminer
    <<: *app
    ports:
      - "8203:8080"
    depends_on:
      postgres:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: empolimer-mqtt
    <<: *app
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  nodered:
    image: nodered/node-red
    container_name: empolimer-nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/settings.js:/data/settings.js
      - nodered_data:/data
    depends_on:
      mosquitto:
        condition: service_started

volumes:
  postgres_volume:
  redis_volume:
  mosquitto_data:
  mosquitto_log:
  nodered_data: